# Generated by Django 5.2.9 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_hotproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_date', models.DateField(verbose_name='精选日期')),
                ('slot_order', models.PositiveSmallIntegerField(verbose_name='展示顺序')),
                ('selection_mode', models.CharField(default='tech4-econ2-mil2', max_length=32, verbose_name='精选模式')),
                ('news_id', models.IntegerField(blank=True, null=True, verbose_name='原新闻ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('url', models.CharField(max_length=500, verbose_name='链接')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('rate', models.FloatField(verbose_name='原始权重')),
                ('selection_score', models.FloatField(default=0, verbose_name='统一展示分')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='图片链接')),
                ('content', models.TextField(blank=True, default='', verbose_name='摘要内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '精选资讯快照',
                'verbose_name_plural': '精选资讯快照',
                'db_table': 'featured_selections',
                'ordering': ['-selection_date', 'slot_order'],
                'indexes': [models.Index(fields=['selection_date', 'selection_mode'], name='featured_se_selecti_50474d_idx'), models.Index(fields=['category', 'selection_date'], name='featured_se_categor_370e22_idx')],
                'constraints': [models.UniqueConstraint(fields=('selection_date', 'slot_order'), name='uniq_featured_selection_slot')],
            },
        ),
    ]
