# Generated by Django 5.2.9 on 2026-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_aisearchtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('author', models.CharField(default='编辑部', max_length=100, verbose_name='作者')),
                ('content', models.TextField(help_text='支持 Markdown 或纯文本', verbose_name='正文内容')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('url', models.CharField(blank=True, help_text='微信文章或外部链接', max_length=500, verbose_name='原文链接')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图片')),
                ('source_type', models.CharField(choices=[('original', '原创'), ('wechat', '微信公众号'), ('reprint', '转载')], default='original', max_length=20, verbose_name='来源类型')),
                ('category', models.CharField(default='原创', max_length=50, verbose_name='分类')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '原创文章',
                'verbose_name_plural': '原创文章',
                'db_table': 'original_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='aisearchtask',
            new_name='ai_search_t_status_a841f8_idx',
            old_name='ai_search_tasks_status_idx',
        ),
        migrations.RenameIndex(
            model_name='featuredselection',
            new_name='featured_se_selecti_61c191_idx',
            old_name='featured_se_selecti_50474d_idx',
        ),
        migrations.RenameIndex(
            model_name='featuredselection',
            new_name='featured_se_categor_41f0f6_idx',
            old_name='featured_se_categor_370e22_idx',
        ),
    ]
