# Generated by Django 5.2.9 on 2026-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_usercomment_utf8mb4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='username',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
