# Generated by Django 5.2.9 on 2026-07-19 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_usercomment_email_alter_usercomment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.originalarticle', verbose_name='关联原创文章'),
        ),
    ]
