language: cpp

os: linux
dist: bionic


compiler: gcc

env:
  global:
    # Dependencies
    - DEPS_DIR="`readlink -f $TRAVIS_BUILD_DIR/..`"
    - OPENCV_BUILD_DIR=$DEPS_DIR/opencv/build

script:
  -  chmod +x opencv_install.sh
  -  ./opencv_install.sh
  -  cd videoRecord
  -  make
