# Generated by Django 5.2.9 on 2026-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechNews",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("rate", models.FloatField(db_column="Rate")),
                ("title", models.CharField(db_column="title", max_length=500)),
                ("author", models.CharField(db_column="author", max_length=100)),
                (
                    "publish_time",
                    models.CharField(db_column="publish_time", max_length=100),
                ),
                ("content", models.TextField(db_column="content")),
                ("url", models.CharField(db_column="url", max_length=500)),
                ("key_word", models.CharField(db_column="key_word", max_length=100)),
                (
                    "category",
                    models.CharField(db_column="category", default="科技", max_length=50),
                ),
            ],
            options={
                "db_table": "techTB",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(default="匿名", max_length=100, verbose_name="用户名"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=200, verbose_name="邮箱"),
                ),
                ("comment", models.TextField(verbose_name="评论内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("is_approved", models.BooleanField(default=True, verbose_name="已审核")),
            ],
            options={
                "verbose_name": "用户评论",
                "verbose_name_plural": "用户评论",
                "db_table": "user_comments",
                "ordering": ["-created_at"],
            },
        ),
    ]
