# Generated by Django 5.2.9 on 2026-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="总页面浏览量(PV)"),
                ),
                (
                    "unique_visitors",
                    models.IntegerField(default=0, verbose_name="独立访客数(UV)"),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "db_table": "daily_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserIPLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "visit_date",
                    models.DateField(auto_now_add=True, verbose_name="访问日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
            ],
            options={
                "verbose_name": "IP日志",
                "verbose_name_plural": "IP日志",
                "db_table": "user_ip_logs",
                "indexes": [
                    models.Index(
                        fields=["visit_date", "ip_address"],
                        name="user_ip_log_visit_d_a19aec_idx",
                    )
                ],
            },
        ),
    ]
