# Generated by Django 5.2.9 on 2026-02-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_dailystats_useriplog"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="产品标题")),
                ("url", models.CharField(max_length=500, verbose_name="链接")),
                ("category", models.CharField(max_length=50, verbose_name="产品类别")),
                ("rate", models.FloatField(verbose_name="权重评分")),
                (
                    "image_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="图片链接"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="来源"),
                ),
                ("rank", models.IntegerField(default=0, verbose_name="排名")),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "每日"), ("weekly", "每周"), ("monthly", "每月")],
                        default="weekly",
                        max_length=20,
                        verbose_name="统计周期",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="周期开始日期")),
                ("period_end", models.DateField(verbose_name="周期结束日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "热点产品",
                "verbose_name_plural": "热点产品",
                "db_table": "hot_products",
                "ordering": ["-period_start", "rank"],
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start"],
                        name="hot_product_period__01cc04_idx",
                    ),
                    models.Index(
                        fields=["category", "period_start"],
                        name="hot_product_categor_3fefa9_idx",
                    ),
                ],
            },
        ),
    ]
