name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: yyjqr/Eangel/@master
      env :
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: pySpider
#         -run echo "test pwd"
        BUILD_SCRIPT: python spider_TechMili_Drive_OPT_V1.8.py
