name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
#     - name: Checkout
#       uses: actions/checkout@master
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Build and Deploy
        uses: yyjqr/Eangel/@master
      - name: List files in the repository
        run: |
          ls -alh ${{ github.workspace }}
      - name: Do my job
#         env :
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BRANCH: master
#         FOLDER: pySpider
# #         -run echo "test pwd"
#         BUILD_SCRIPT: python spider_TechMili_Drive_OPT_V1.8.py
      - run:  pip install bs4
      - run:  cd pySpider
      - run:  echo "test python dir"
      - run:  ls -alh
      - run:  python spider_TechMili_Drive_OPT_V1.8.py

